// Copyright 2025 toni experience software GmbH
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_automotive/src/messages.g.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PropertyUpdateEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return PropertyUpdateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

abstract class TestHostFlutterAutomotiveApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding => TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<Object?> getProperty(int propertyId, int areaId);

  Future<void> setProperty(int propertyId, int areaId, Object? value);

  void subscribeProperty(int propertyId, int areaId, double updateRate);

  void unsubscribeProperty(int propertyId, int areaId);

  bool isPermissionGranted(String permission);

  void requestPermission(String permission);

  static void setUp(TestHostFlutterAutomotiveApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.getProperty$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.getProperty was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_propertyId = (args[0] as int?);
          assert(arg_propertyId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.getProperty was null, expected non-null int.');
          final int? arg_areaId = (args[1] as int?);
          assert(arg_areaId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.getProperty was null, expected non-null int.');
          try {
            final Object? output = await api.getProperty(arg_propertyId!, arg_areaId!);
            return <Object?>[output];
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.setProperty$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.setProperty was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_propertyId = (args[0] as int?);
          assert(arg_propertyId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.setProperty was null, expected non-null int.');
          final int? arg_areaId = (args[1] as int?);
          assert(arg_areaId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.setProperty was null, expected non-null int.');
          final Object? arg_value = (args[2] as Object?);
          try {
            await api.setProperty(arg_propertyId!, arg_areaId!, arg_value);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.subscribeProperty$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.subscribeProperty was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_propertyId = (args[0] as int?);
          assert(arg_propertyId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.subscribeProperty was null, expected non-null int.');
          final int? arg_areaId = (args[1] as int?);
          assert(arg_areaId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.subscribeProperty was null, expected non-null int.');
          final double? arg_updateRate = (args[2] as double?);
          assert(arg_updateRate != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.subscribeProperty was null, expected non-null double.');
          try {
            api.subscribeProperty(arg_propertyId!, arg_areaId!, arg_updateRate!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.unsubscribeProperty$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.unsubscribeProperty was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_propertyId = (args[0] as int?);
          assert(arg_propertyId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.unsubscribeProperty was null, expected non-null int.');
          final int? arg_areaId = (args[1] as int?);
          assert(arg_areaId != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.unsubscribeProperty was null, expected non-null int.');
          try {
            api.unsubscribeProperty(arg_propertyId!, arg_areaId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.isPermissionGranted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.isPermissionGranted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_permission = (args[0] as String?);
          assert(arg_permission != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.isPermissionGranted was null, expected non-null String.');
          try {
            final bool output = api.isPermissionGranted(arg_permission!);
            return <Object?>[output];
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.requestPermission$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.requestPermission was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_permission = (args[0] as String?);
          assert(arg_permission != null,
              'Argument for dev.flutter.pigeon.flutter_automotive.FlutterAutomotiveApi.requestPermission was null, expected non-null String.');
          try {
            api.requestPermission(arg_permission!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
